services:
  - type: web
    name: grocery-index-frontend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://grocery-index-api.nicklina.com/api/statcan
      - key: NODE_VERSION
        value: 20.19.0
      - key: PORT
        value: 5000
    buildFilter:
      paths:
        - react-frontend/** 